<a href="https://colab.research.google.com/github/RS2107-QUANT/MNIST-DATASET-PROJECT/blob/main/MNIST_PROJECT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torch.nn as nn
import pandas as pd

In [2]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score

In [3]:
from sklearn.datasets import fetch_openml

mnist = fetch_openml('mnist_784', version=1, as_frame=True)

X = mnist.data
y = mnist.target
y=y.astype(int)
X=X/255

In [4]:
class ANN(nn.Module):
    def __init__(self):
        super().__init__()

        self.network = nn.Sequential(
            nn.Flatten(),
            nn.Linear(784, 128),
            nn.ReLU(),
            nn.Linear(128, 64),
            nn.ReLU(),
            nn.Linear(64, 10)
        )

    def forward(self, x):
        return self.network(x)

model=ANN()

In [5]:
optimizer=torch.optim.Adam(model.parameters(),lr=0.001)

In [6]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.142857)

In [7]:
X_train

,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,pixel10,...,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,pixel784
18293,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
37237,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
45711,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
58396,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
65443,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5969,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29131,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
38416,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
50566,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4057,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [8]:
y_train

18293    1
37237    1
45711    5
58396    0
65443    0
        ..
5969     4
29131    8
38416    6
50566    0
4057     5
Name: class, Length: 60000, dtype: int64

In [9]:
X_train_tensor=torch.tensor(X_train.values,dtype=torch.float32)
y_train_tensor=torch.tensor(y_train.values,dtype=torch.int64)
X_test_tensor=torch.tensor(X_test.values,dtype=torch.float32)
y_test_tensor=torch.tensor(y_test.values,dtype=torch.int64)

In [10]:
y_pred_train=model(X_train_tensor)
y_pred_test=model(X_test_tensor)

In [11]:
loss_func=nn.CrossEntropyLoss()
loss_train=loss_func(y_pred_train,y_train_tensor)
print(loss_train)

tensor(2.3038, grad_fn=<NllLossBackward0>)

In [12]:
for epoch in range(25):
  optimizer.zero_grad()
  y_pred_train=model(X_train_tensor)
  loss_train=loss_func(y_pred_train,y_train_tensor)
  loss_train.backward()
  optimizer.step()
  print(f"Epoch {epoch+1}: Loss {loss_train.item()}")

Epoch 1: Loss 2.3038277626037598
Epoch 2: Loss 2.273904323577881
Epoch 3: Loss 2.2445266246795654
Epoch 4: Loss 2.2109320163726807
Epoch 5: Loss 2.1719651222229004
Epoch 6: Loss 2.1277246475219727
Epoch 7: Loss 2.07859468460083
Epoch 8: Loss 2.0247817039489746
Epoch 9: Loss 1.966627597808838
Epoch 10: Loss 1.9046074151992798
Epoch 11: Loss 1.8393168449401855
Epoch 12: Loss 1.7714924812316895
Epoch 13: Loss 1.7018073797225952
Epoch 14: Loss 1.630774974822998
Epoch 15: Loss 1.5589185953140259
Epoch 16: Loss 1.486817717552185
Epoch 17: Loss 1.4150758981704712
Epoch 18: Loss 1.3442625999450684
Epoch 19: Loss 1.2749183177947998
Epoch 20: Loss 1.2075268030166626
Epoch 21: Loss 1.1424705982208252
Epoch 22: Loss 1.0800516605377197
Epoch 23: Loss 1.0205219984054565
Epoch 24: Loss 0.9641302824020386
Epoch 25: Loss 0.9111152291297913

In [13]:
y_test_pred=model(X_test_tensor)
loss_test=loss_func(y_test_pred,y_test_tensor)
print(loss_test)

tensor(0.8598, grad_fn=<NllLossBackward0>)

In [14]:
from sklearn.linear_model import LogisticRegression
log_reg=LogisticRegression(max_iter=100)
log_reg.fit(X_train_tensor,y_train_tensor)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [15]:
y_pred_log=log_reg.predict(X_test_tensor)

In [16]:
log_accuracy = accuracy_score(
    y_test_tensor,
    y_pred_log
)

log_precision = precision_score(y_test_tensor,y_pred_log,average="weighted",zero_division=0)
log_recall = recall_score(y_test_tensor,y_pred_log,average="weighted",zero_division=0)
log_f1 = f1_score(y_test_tensor,y_pred_log,average="weighted",zero_division=0)
print("Accuracy:", log_accuracy)
print("Precision:", log_precision)
print("Recall:", log_recall)
print("F1 Score:", log_f1)

Accuracy: 0.9231
Precision: 0.9228987855230536
Recall: 0.9231
F1 Score: 0.9229492567319186

In [17]:
from sklearn.ensemble import RandomForestClassifier
clf_model=RandomForestClassifier(n_estimators=100)
clf_model.fit(X_train_tensor,y_train_tensor)

RandomForestClassifier()

In [18]:
clf_model_pred=clf_model.predict(X_test_tensor)

In [19]:
rf_accuracy = accuracy_score(y_test,clf_model_pred)
rf_precision = precision_score(y_test_tensor, clf_model_pred,average="weighted",zero_division=0)
rf_recall = recall_score(y_test_tensor,clf_model_pred,average="weighted",zero_division=0)
rf_f1 = f1_score(y_test_tensor,clf_model_pred,average="weighted",zero_division=0)
print("Accuracy:", rf_accuracy)
print("Precision:", rf_precision)
print("Recall:", rf_recall)
print("F1 Score:", rf_f1)

Accuracy: 0.9701
Precision: 0.9701298656207633
Recall: 0.9701
F1 Score: 0.9700754220926064